<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-24T01:11:24 GMT-08:00" name="Suite" finished-at="2022-02-24T01:12:33 GMT-08:00" duration-ms="69534">
    <groups>
    </groups>
    <test started-at="2022-02-24T01:11:24 GMT-08:00" name="Test" finished-at="2022-02-24T01:12:33 GMT-08:00" duration-ms="69534">
      <class name="InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle">
        <test-method is-config="true" signature="startup()[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:11:24 GMT-08:00" name="startup" finished-at="2022-02-24T01:11:42 GMT-08:00" duration-ms="17450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method signature="testCase_0001(java.lang.Object)[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:11:42 GMT-08:00" name="testCase_0001" data-provider="testdata" finished-at="2022-02-24T01:11:55 GMT-08:00" duration-ms="13673" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Vehicle_ListPrice=888, Product_startdate=44177, PriceValidation_Gold=238, TC No=1, Vehicle_Annual Mileage=100, Product_insurancesum=5.000.000,00, Vehicle_Date of Manufacture=43564, Insurant_Hobby=Speeding,Other, SelectOption=Silver, PriceValidation_Ultimate=2621, PriceValidation_Silver=69, Vehicle_Make=Honda, Vehicle_Engine Performance=666, Insurant_occupation=Farmer, Vehicle_No of Seats_motorcycle=2, Insurant_LastName=NNN, Insurant_ImageFilePath=??, ProductOptional_Products=Euro Protection, Vehicle_Model=Motorcycle, Insurant_country=India, Insurant_zipcode=444061, Product_damageinsurance=Partial Coverage, TC Name=Verify Insurance Premium for Honda MotorCycle, Vehicle_CylinderCapacity=333, PriceValidation_Platinum=1376, Insurant_FirstName=Jayant, Insurant_birthdate=32854, Insurant_gender=Male}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [69] but found [236.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [69] but found [236.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle.testCase_0001(EndToEndTests_Motorcycle.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase_0001 -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:11:56 GMT-08:00" name="afterTest" finished-at="2022-02-24T01:11:57 GMT-08:00" duration-ms="1263" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="startup()[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:11:57 GMT-08:00" name="startup" finished-at="2022-02-24T01:12:06 GMT-08:00" duration-ms="9191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method signature="testCase_0001(java.lang.Object)[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:12:06 GMT-08:00" name="testCase_0001" data-provider="testdata" finished-at="2022-02-24T01:12:12 GMT-08:00" duration-ms="5896" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Vehicle_ListPrice=888, Product_startdate=46003, PriceValidation_Gold=238, TC No=2, Vehicle_Annual Mileage=100, Product_insurancesum=20.000.000,00, Vehicle_Date of Manufacture=36990, Insurant_Hobby=Speeding,Other, SelectOption=Gold, PriceValidation_Ultimate=2626, PriceValidation_Silver=69, Vehicle_Make=Volvo, Vehicle_Engine Performance=900, Insurant_occupation=Farmer, Vehicle_No of Seats_motorcycle=2, Insurant_LastName=NNN, Insurant_ImageFilePath=??, ProductOptional_Products=Euro Protection, Vehicle_Model=Scooter, Insurant_country=Sweden, Insurant_zipcode=444061, Product_damageinsurance=Partial Coverage, TC Name=Verify Insurance Premium for Volvo Scooter, Vehicle_CylinderCapacity=900, PriceValidation_Platinum=1379, Insurant_FirstName=Anita, Insurant_birthdate=28471, Insurant_gender=Female}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [69] but found [720.00]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [69] but found [720.00]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle.testCase_0001(EndToEndTests_Motorcycle.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase_0001 -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:12:12 GMT-08:00" name="afterTest" finished-at="2022-02-24T01:12:13 GMT-08:00" duration-ms="1173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="startup()[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:12:13 GMT-08:00" name="startup" finished-at="2022-02-24T01:12:26 GMT-08:00" duration-ms="12912" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startup -->
        <test-method signature="testCase_0001(java.lang.Object)[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:12:26 GMT-08:00" name="testCase_0001" data-provider="testdata" finished-at="2022-02-24T01:12:30 GMT-08:00" duration-ms="3786" status="FAIL">
          <params>
            <param index="0">
              <value is-null="true"/>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "java.util.HashMap.get(Object)" because "hm" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.HashMap.get(Object)" because "hm" is null
at pageObjects.EnterVehicleDataPageObjects.enterVehicleData(EnterVehicleDataPageObjects.java:75)
at InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle.testCase_0001(EndToEndTests_Motorcycle.java:27)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase_0001 -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle@55795845]" started-at="2022-02-24T01:12:31 GMT-08:00" name="afterTest" finished-at="2022-02-24T01:12:33 GMT-08:00" duration-ms="2275" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- InsuranceCalculation_Motorcycle.EndToEndTests_Motorcycle -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
